hash-format = "sha256"

[[files]]
file = "README.md"
hash = "b674c6de401a80e4177b925ba5d4a4acb30060274d23fa7677a12b28e88d7aac"

[[files]]
file = "config/drippyloadingscreen/early_window_reference.properties"
hash = "d7c4eeb49268b2b828b16dddf7112911f91d08b275969654b44c878dc7693c18"

[[files]]
file = "config/drippyloadingscreen/options.txt"
hash = "c78f6fd50d3b0440993961585a5b59be1f8dbe035611d1843f96ff7056ffcc04"

[[files]]
file = "config/fancymenu/assets/banner1-removebg-preview.png"
hash = "1b689d77e6fbaf966fbbe5d010a967ece35158e283eb6dc6f049b574f7b4d08b"

[[files]]
file = "config/fancymenu/assets/banner1.png"
hash = "3685a9dfe9abe7cea9c092dc0e4de9c6339ff67c8bdedb34ede272a452cb26d9"

[[files]]
file = "config/fancymenu/assets/fullbanner1.png"
hash = "d9258bad6db693c8239b77d0d2f1f7534512449123db4945f21b17fdfbcc634b"

[[files]]
file = "config/fancymenu/assets/logo1.png"
hash = "f4c052798ecf4c0c18c59b814b61f0233ad831365eac2e4f8aa9b3cbabdf81e0"

[[files]]
file = "config/fancymenu/assets/mcbg1.png"
hash = "1a2de784bed1b993f48c6134da5c936550a8d54f2947e00a30339cda1f0469ea"

[[files]]
file = "config/fancymenu/assets/server-icon.png"
hash = "49319633b594c9f5a497b6c4124f823888b07143bab6ee3cbef92a4738f8ec72"

[[files]]
file = "config/fancymenu/custom_gui_screens.txt"
hash = "ff492043eaf454c46e949d5eef32ece90cc5a19feb50a161dd29a43b5732c880"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "d00cb033aaf8cee4e560bef3a1c46c52aaa445c2ad47a1cdb801c9e488d7a53d"

[[files]]
file = "config/fancymenu/customization/CreateVC-Layout.txt"
hash = "1f17b597d2c20543ee3161f811ed6b808ee715eb8ae12886a1995dc4787f2f41"

[[files]]
file = "config/fancymenu/customization/claim_layout.txt"
hash = "be4d5945812f4da93c1aad853f769d1340055547a0a1341aef3859144a788e93"

[[files]]
file = "config/fancymenu/customization/drippy_loading_overlay_layout.txt"
hash = "3452ed95afca11e6b917be3e39f2e8ff9609ba4e5cd2be6a088d93ea4da00260"

[[files]]
file = "config/fancymenu/customization/join_multiplayer_screen_layout.txt"
hash = "eadcfd110d2b7f8d7d7489b789624fad095bd8347942cc5c0e5db10bfcc7e85d"

[[files]]
file = "config/fancymenu/customization/xaero.pac.client.gui.mainmenu_layout.txt"
hash = "059b05e0c46fe042446c28a5b1ddb94d72fa22d5832ea9982818b2f3026fb4ea"

[[files]]
file = "config/fancymenu/layout_editor/widgets/element_layer_control.lewidget"
hash = "051d700ea7ff1bd626063d60f9a9cd65a0af1fed5903706d1e70fce20bcb2495"

[[files]]
file = "config/fancymenu/legacy_checklist.txt"
hash = "9a25d3dc708e43eabafce5479a13c02dae15bc7f673afb2745b8b2ba48a97dc0"

[[files]]
file = "config/fancymenu/options.txt"
hash = "4f78e50cea6282a4ee3e5a84a190ce7e150c843f8e22734ce5047e3d1c63d960"

[[files]]
file = "config/fancymenu/ui_themes/dark.json"
hash = "3f1263eaf693fdb6a315099b06797ac18830faa66c620916a80337a5082fd850"

[[files]]
file = "config/fancymenu/ui_themes/light.json"
hash = "3fcfc5f9957fbb86aea846c9ad49a24f47ca709c523c4018b584668e38b72f41"

[[files]]
file = "config/fancymenu/user_variables.db"
hash = "3d7d4cda73d6bde134a568ccbe4e8d2e7fbe701570012b71fa45acdb2258c823"

[[files]]
file = "config/info.txt"
hash = "806eb0596a43a1d8deec50fbd0a1711a52c2bc5dc5982170b6fd08772828cf59"

[[files]]
file = "icon.png"
hash = "49319633b594c9f5a497b6c4124f823888b07143bab6ee3cbef92a4738f8ec72"

[[files]]
file = "instance.png"
hash = "49319633b594c9f5a497b6c4124f823888b07143bab6ee3cbef92a4738f8ec72"

[[files]]
file = "kubejs/README.txt"
hash = "989f3737ae4621b8ff6730bce4cbeeee756921e7e510e0c281c8a350501d98af"

[[files]]
file = "kubejs/config/common.json"
hash = "e00a67922942660d77c213379b5128a46c5abc894178b0be04006d325ff5f6b3"

[[files]]
file = "kubejs/config/openpartiesandclaims-server.toml"
hash = "f11457c96d3773bb3aafab138130946bd38b9597bd4b29cbb53fd6b804b0dfdd"

[[files]]
file = "kubejs/config/web_server.json"
hash = "b1a77bd219c205b05bce31e5837f6c505db0b1cc72b69efabfc3ed27dc1dd59d"

[[files]]
file = "kubejs/server_scripts/Scripts/claim.js"
hash = "d0e4d57b346f6e0fc11d2d04cf9b97bf430683fd9739c85cd8e11db5643f3cb8"

[[files]]
file = "kubejs/server_scripts/Scripts/serverClaimBuy.js"
hash = "a92b7c339a16ae7b29be5455010a3f09a58a178acba3a28620dd85be79005aca"

[[files]]
file = "kubejs/server_scripts/main.js"
hash = "dae099ae3be7f033c0c190ee8c3b023b42f6b235d9d0591be5926e8435dbd67f"

[[files]]
file = "kubejs/startup_scripts/main.js"
hash = "5c4659e7bb368960801ccfce24ac3493fa14aae88a7e17b2a9cdfe1931985ffe"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4ca8b963965342aafdfe251e5306259eb9cf459d43e46d9695974dcff01465aa"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/baguettelib.pw.toml"
hash = "e8ed8e243655cb6d2026fa62280217ad0cba128d352386b53b397b1175d3d3cb"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "86cf2ae835b8f3d981af2e88a4d19fdc3dc4f5aa3904c6ba30e25d77d3e9fcbb"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "2b4c244aa7a303dead0a1b659c25b9b9bce2ced2758ea55aca347556f7348189"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "1d5cc2b6dcfd1fc3adba4566b1c29b57ff1175316678c1f22e63cbc3e28a5ba0"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2e6a2f8c477128a76ef059dfef7ca8a1befa2ae0ebe7ae2171e716f0c905cd00"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "531d3dd3deb7479e3fd1496a7c2db8606bc7affa33fc57eccddc9904c0ac559e"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "ccf9e64814aea3a7c29689a9f2509002976428bdb798119cb32cdbd655456a07"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "42ffb6f5835250003da6ca3667ff751709ea295faee43b49c365b0f6c1e8f4d8"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "e3d0e6da51df08d87c9b88fd6b4011de711d95497263b9ecfd1466cbd34b98d5"
metafile = true

[[files]]
file = "mods/corpse-x-curios-api-compat.pw.toml"
hash = "0dbb09999d85aa27cae3b923827245ad2e9559bb46f69736dde8f0377fd1c7e2"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "e2edf339c98dbdcf04f46a15276e9b1b5bbdeee0f1ac8b7d9bddb1ee8e54b9a1"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "d3ea4ea3cc70a32321ac897cc50f97b2bb84b5c333d7cf04615d41c620345161"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "64f8e839da919268f5ecdf1df17f466c08befa6048f8b2cadf8897b126fb0976"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "6f02f0f280eb14063e3cc7bf26fa1a8173c1295e9e4d83bc1062ee933436844f"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "6a5638b1888c9c882ea5cd45bc93aab958a50fd302cb7e9af3c807a2b46c9497"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
hash = "5c0f5c8f654d1c35bd36ed86e75216b84076f0a093e04bb4bd25e22a8de4fb82"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "979632aae1dad7f82a5a1a34ea1c5844f9584129d4fa5677c28b32cb319b6fd7"
metafile = true

[[files]]
file = "mods/create-escalated.pw.toml"
hash = "427fc2d73e185e6c1d653c87f014eaf7e009019524ba3a32602bf052e33553ec"
metafile = true

[[files]]
file = "mods/create-liquid-fuel.pw.toml"
hash = "ec65f48e74ac39be1d5a99e0bc74fd1013abd9efcf361e52043990ff5fba4c2b"
metafile = true

[[files]]
file = "mods/create-mobile-packages.pw.toml"
hash = "693fa0a7818255f6bd0f64dac46bd3f306d4f180f3c201ce6bbf58692e7b9b3e"
metafile = true

[[files]]
file = "mods/create-netherless-ported.pw.toml"
hash = "88b67f57a9c31b9684f7840b612eafb10b977393eb2025786443ee1c771e5af3"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "2259e97a3de21e9d29e4a351288f92334092f17d782b2e079fb8733babcad646"
metafile = true

[[files]]
file = "mods/create-stuff-additions.pw.toml"
hash = "3a37f452485e16f15a044572da46c48891015ae86c78d8268cb77078e6ca4f4f"
metafile = true

[[files]]
file = "mods/create-winery.pw.toml"
hash = "196733aacff77babcd3c6c79a27a5ca300dd12061bb121deed56c614fa8a7723"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "eb7b4a7b28d4806c7bb7a0cf84f4dca90fc5d62317573e9100542bc484a48750"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "90bf9f547b4c3c76873d51f13c355f769e5043691f56d3a8744bad10ab0fd70c"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "92d8711662b4e3fd42a57254571aca9f0b33a10bb7492a8fba59b22e78f688e6"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "f92e7a06645e41ea1934dc420eb2772edb1708c0d71cb427baef8cf753acb934"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "db153992e71c2c1ca7643ad93d11f1276cada2843879cd01909abef2f2ed9df9"
metafile = true

[[files]]
file = "mods/diagonal-walls.pw.toml"
hash = "36899ae409d7c9bf4a5b322328f3eba6c8de4812a4f8594140a4953b05d62f88"
metafile = true

[[files]]
file = "mods/diagonal-windows.pw.toml"
hash = "5280e0bcfa648658c572b9ffa12ff5e39374923b30c732d3ceff4ae7ed9228ff"
metafile = true

[[files]]
file = "mods/discord-chat-connect.pw.toml"
hash = "2875724e5b15aac10acf6af0f0c111cefe64f7dbfed580ea285ef90dbde9b1ec"
metafile = true

[[files]]
file = "mods/drippy-early-loading-module.pw.toml"
hash = "368fe4fde8eeb1e3de62b0172bdfd8bba278793c7a46d4da8e64a7074e6dda4c"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "98e02478bc3be30b8eb4e62b8fb116a5805caea3cf557f17d36c633d840fe223"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "f619c1ed2e189f9d482d081411fccee4bd26c05cce52a5db914f1989303f080c"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "541520814421d829976fbb2162e7a195b18e9d82ed3b3c8dc9c7fbc50b2cb491"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "efce6a511bf4a60c64fe082fd183c9cd693861fb79413ba540cb1053ff562191"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "32078c39569bbb4b33d2d86a09cfc18a9f5b63a11d0ba2b186fd07341e422c92"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "732230fce4618b7b3f399e48a9fa632731ebbf4226e39cbcdac06586be15dd5f"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
hash = "9237b88b063c87c5f4b5a79c5ff8a7c287537f3deabe04027efee8298ac380dd"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "eeccd885575c012a8d0a34fc7e8926f2e46da0e0f7389b1ed6c4904991603675"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "1fc8ab07ea6f6abf5252a680f4ee72d7feaa652bc6b17214b1ddc5f5fe4c5d6d"
metafile = true

[[files]]
file = "mods/emiffect-status-effects-emi-plugin.pw.toml"
hash = "08b5fe6bbf5980820af8addc37e5ee41e48756400d86f9f554222f27b3ccecb5"
metafile = true

[[files]]
file = "mods/emojiful.pw.toml"
hash = "f217d51e614f0a27228a88ac581cb4e9dd26b4c549a55c79cd9c4e054b2450c3"
metafile = true

[[files]]
file = "mods/emotecraft-forge.pw.toml"
hash = "41da9deeec5e9e6f3369f890a9f459d3dae3edf59c7072cb7c5dd26b953bf7d7"
metafile = true

[[files]]
file = "mods/etched.pw.toml"
hash = "f2be475fad96949ff8e26e8a03046b1732935b1dbd9b8824e505e7413ec08622"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "2d7e927b0efdc5e79a50505151975605b355d14d7da2a475aa8a767697911651"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "f407238ae37effcd669f828b80a7246e805bc099b4848cd550b1d2d428fea78b"
metafile = true

[[files]]
file = "mods/fast-async-world-save-forge-fabric.pw.toml"
hash = "c19754832997fe5fbd9488eeb3b02f3221f36893f94003e403b731ed9e9132ce"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "689c52c2efefe8cd4489fbcee01d557d45ad339dfb02f872e1097889928eef71"
metafile = true

[[files]]
file = "mods/ftb-essentials.pw.toml"
hash = "2e8d41553147e5470a9f31303cb440f106cefde0dfc13c30cf69b8248b70644c"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "e3ae8c4681615395d7fb3373e8eb1d99d6e3f4c66703c9f18bb4a8f6cbfcd215"
metafile = true

[[files]]
file = "mods/functional-storage.pw.toml"
hash = "0092f83b6663191fb947110c2b51a5213daea995da831d7de0a769cf4c353cd8"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "c595b64a055d987de9d4ce6156c88eec58cf1b1ade849ff11731307f64a60941"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "402ca5410076adcf4bff4211d5d734572e0549955d3613ea0942309ec29a409b"
metafile = true

[[files]]
file = "mods/hypertubes.pw.toml"
hash = "372eb20ef958e81c0741a1c76654d55389ce6702cc38adb8bc9804c2da489386"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "a17d2ad6bc1592564a6bdda0c17ceb641bfe3d0842d96cd8aa3f4fbc2d1ebafe"
metafile = true

[[files]]
file = "mods/immersivemc.pw.toml"
hash = "767808a646774f88a4a265e78c8278c7c5aa69e2479b3dbd00ec3df14e7c01fa"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
hash = "89420f657cec1038646f75531ae388e92d27c51c84b1f121e935ae5aecf995be"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "6b3f722168fa57e23fca5441d9b74a11194d9252625d6bf0898c4d212f99380a"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "540706ab9db0907199fcc08ac62c8f0b291f7ce5b01a90e426f0b6c76c76b51c"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "054a1887da4f14b791910660a2a7a2035ac1382461b881a65fe07b224c03735f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7fbe3225c134e823a07f3aecedace39fe866f327671ecca928f134399b94008d"
metafile = true

[[files]]
file = "mods/kubejs-create.pw.toml"
hash = "21a5deb5da882d9f3eb4eaf7f0cf77f52737e1e6b44d2f691bf10fda9c86d790"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "395ed890024bdb90e7c0fed1edf8b3905a367942ded954fca92384c76a7e5601"
metafile = true

[[files]]
file = "mods/lmft.pw.toml"
hash = "1b78273918bdbfe66d38f35b6ec2fbaa7e862fb9dca67cc99a725df768365e96"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "e569c2679310179fdd1cf1e4af72117c620f7d5d6776fdb9def8d60d1263d99d"
metafile = true

[[files]]
file = "mods/maintenance-mode-forge-fabric-quilt.pw.toml"
hash = "421ae73f3d143681f4b527256020513f021e37616ff6eb1aa731ae2ad7f6842a"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "9dff522b00f5269538d0351536f34b22384996de30be454ef1369f1b1e5c1aeb"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "97521b85e74dfbc642b9102a46be0cdda07b9cfe36aba027a3878054f93ccfcb"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "2bdee19bd39b4bd411d7c858a7978ca9d2bdda41c1cf15920ea6be0014663f79"
metafile = true

[[files]]
file = "mods/neoculus.pw.toml"
hash = "47bf43b1382c3df649c7c7db0c43ffdf61fb80b642d59e98743db61fab11961d"
metafile = true

[[files]]
file = "mods/not-enough-crashes-forge.pw.toml"
hash = "32b9515e4f9a0ccbf91f88e67ef33319aab272e12e09e0c6b227d7be8238bfee"
metafile = true

[[files]]
file = "mods/numismatics.pw.toml"
hash = "803cee33e53713a18f631ec6255c322815988ef4b590ee5a1187f1402111d1f9"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "32f8d722b8e90a4ded120d3cbc7d6718d7bc2ea57a292af725978117710a6490"
metafile = true

[[files]]
file = "mods/opac-bonus-claims.pw.toml"
hash = "ebf498efc7d46c761dbef61bf69af37500c962fbf7d8aa8cd86f153ccb77e2b7"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "36a7e297b2831318190137b0fc73a8a9855f70d2f14cb8a5f6dc27360986a869"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8b725f1822c0feab9e51bef600f2ee6f4c26efbb55aa3ee9073a027f1f134202"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "804736be3ded2a6f89f44522b88d82636209ed203c234ea34b6d6ffdd9ecee54"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "b1e0e7bf562eb6a1eb939835c19bbc56c46d209eeba8f2b766c0ad39676a389a"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "75ff68dd0bfb30f2ff97f170ffbb74d5b6aaa791416c4a0559d09ac8778561ba"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "b4ea87bc5953a1a0eec5207bb3182285e3301e87afa64fb1c8a4a8e993e915ea"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6c0fac550bb053ee2728144a28819835823dcc6d04ad7897750431fe55100e53"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "78e3dde88f8a9b30ab337d824238df20c54f1cd283b2c5db8511f827bb9f8e9b"
metafile = true

[[files]]
file = "mods/smooth-boot-recreated.pw.toml"
hash = "1496e2641db049b31cbc8b5ff8d7f6355cba879360cab78e88ca370b4a795ffb"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
hash = "ff6934dbf3203c63dbdab3b2b3a89e82c047ad22db63d8511d737a489aac743c"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "c966ea02eb59f31dcaeaebe9d96c9b232a2fb16d2fe971729350e567a4ff1bd7"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "ec485dec0a45ec2b1865487f4f704a9c3eb05be54e67db1309a27d4f4fbe839c"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "9a51a08d9f91b14ac0fd2039df616ae82dbd92dcb518347e8a5d2ab8ed5e2390"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "6d9eaf43c14c66465e87bf03cc5cb5ecef57b3f2e8063c52f6332d33689d30be"
metafile = true

[[files]]
file = "mods/tacz-1-21-1.pw.toml"
hash = "c4aa01a3ea8c931ae903a51a3b6808a42d48e8ef73fe1681116f9aeaecd82bd6"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
hash = "de4e42a8d1496f13ddd6c54f291e87e0e802c0deb08ef37daf8d2887c8657ee3"
metafile = true

[[files]]
file = "mods/torchmaster.pw.toml"
hash = "23ea2c32834281723c63d45ffe42969172492d36309755a46bc47154c3014b3f"
metafile = true

[[files]]
file = "mods/vanishmod.pw.toml"
hash = "08b22ddf3f634e34ab38470ef3039ad521463236d6a5c6f90e8637aa5cba7c7e"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "f28ceb27bc3ed0a9825de1f853d177b69495deab9128aa05694616e4504ddb52"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
hash = "3e2708aea2f7537c089dd27a03dcf1f36eb52ff57a2937e809cafe179b6ffe94"
metafile = true

[[files]]
file = "mods/voiceless-survival.pw.toml"
hash = "6e4805e2c0f894d829ef9c252e80bcb7ee71adaaf8cec27e403088c37e807efe"
metafile = true

[[files]]
file = "mods/waddles.pw.toml"
hash = "0e355cc48486d2349ac810a250075f85f667f59e63b98ed5046059773614c75c"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "f2dfce29433a6b2a3349db5f4913f4077c74d2e7982c8c4ec51fac5ab09d21ad"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "3c9d3c4a6cf4016aebd324fd4cdf6332da89c7f41912e41f56f08c6947d66e2d"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "feb67f4e3a254fafda303ccdb989354524aaa29bd26f1cc0013764b9f93040d9"
metafile = true

[[files]]
file = "options.txt"
hash = "1b34706988b2413b9260ce3e1ae49d5fc37051fc7686517d1c98ddc3dbde8e89"

[[files]]
file = "servers.dat"
hash = "ee632068fe3b73aeee150b7176b4da451c58eaf6579307ea7df91d327991cdc0"

[[files]]
file = "servers.dat_old"
hash = "ee632068fe3b73aeee150b7176b4da451c58eaf6579307ea7df91d327991cdc0"
