name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cb61bcd63071f75ed9658607522c986c4a67b5b35a1472e01c75826429588ce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
