name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edd11de01570c31b612fa6a86f3ea9d7285eaef87d185776d7060a3bfafc2a48"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
