name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de28c52ab282dd290ce0ecba86bac25b25f820ef54c21430542286ba7965cfc2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
