name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17b8f9025c0317f658903d645bce4782ded1739876bd16e0dbb6182e6dc0c0fd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
