name = "CreateVC"
author = "Jammersmurph"
version = "7.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba74b224dd58e7e53c21a2463bea482443074b80269055bf9393586510717a97"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
