name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abfe3376077ae09e7a24c6739ccea9b1a627ab7f199c4c890f89079b3ca2c0de"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
