name = "Create VC"
author = "Jammersmurph"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdc010ccf36329fd67d033e5b84acfa49861bdb7fc9c805b3b060c083d74b5ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
