name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ece61e7409bbdfcbefec43254c9ef604956f5b434984f77886304ba849179aa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
