name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69b989f2740577fc6a91e687d2ab5fe0338392800bede0e2c0d29042095c24fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
