name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21b5a38abaf29c0bd8d8e2527d04747b4c74eedb8f49c9aacee5b4c7019819f2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
