name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0bc4f0b5074cee666220da17e85b6382f0f9d909f5b439ee1e9fae536ba02bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
