name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ebc9373ef1d9f7a684d16da38eee8003a41b9ea535842d5da76c322536f7e99"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
