name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f61e4a16961f82b669c158e52a1b3755dd026b7bbc69908c20e1e453c4276e4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
