name = "Create VC"
author = "Jammersmurph"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb7f1833d8f1adc45f5697f2486594c7741353003a552a9a26b3b7747f51850e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
