name = "Create VC"
author = "Jammersmurph"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40e9db6a3a3248829115d6294871c83337f262bca72f888d04b4fc23d16dc285"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
