name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc8c1ebec561d9c43c6636d9fa609834c5ea0bbf6e8d1a165ca26a2759bdfd15"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
