name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdff4b220e8ceea7324954ad43fbae2f333002939bb76052e07d4bd190ead5fe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["neoforge"]
