name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8e0aeb53c0f88017dfdf734cdeadc8b0e19362a216db0581a3866e4fd11c2fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
