name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "444c9a88488d55d30a1cfa59db41fa313c4015cecc55b00643cf33b689cf3206"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
