name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45c69b7a9c2ae6d208fe70981d8f060cff32046485549dda00d17320beddbdac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
