name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4a6a649e758c481c824e49a7f76ff0bb1eb397f2844dc2502021c77c39a3893"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
