name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9298dd2edc94a615092c7cc9576c375465e94c06ab8ef74cfc5aa7a552285cc6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
