name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "376c794f7774d4eb9e3141335778bff8fba1635948f03bb5bf51dafde2d767bd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
