name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "199ec6e6f91a4949288c6fd4eed3c37b4e1eaccfe63901bb3c27b46fbd11db01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["neoforge"]
