name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64da258c90c666d2f60db05f0fde5888db7ffccf21a3dff0041a6387a2d42d7b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
