name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dced2f9e7bd8bc06f7ca09a8c45366cbaad6a5fad468171a0c01f36f41e7014f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["neoforge"]
