name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6997ed75d0cd10a6f9ab37ddab832f877cf574162dfc3523e8484993cbeddcf2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
