name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0b7f686b42170319f51a0cd8398a08deddc8bad3112ebe3398f75289b41d389"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["neoforge"]
