name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f2b840eca4d378dee71dc9266d08e572d6d7983550e362387cf305377def82c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
