name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddb580f8c04812a97819ca5de1c7a7b5aa9bbc3554872cd7890c7d4f260642d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
