name = "Create VC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34dc395db3f0d95bb3fcab9fb0bb63b7fc092a3d18061107bf025bbdd4141852"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
